### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger

### ISSUE THREAD

**Issue by StrikeFreedomX** [StrikeFreedomX/log4j#1]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

1. I submit log4j into my maven project
2. There is no problem with running in IDEA
3. Packed into a jar package,  run the jar package and report an error
![error](https://user-images.githubusercontent.com/48379324/66481776-2cf91b00-ead4-11e9-9145-a99677cc960d.PNG)
![捕获](https://user-images.githubusercontent.com/48379324/66481777-2d91b180-ead4-11e9-9e2c-d53f96642e13.PNG)

**Comment by StrikeFreedomX** [comment]
> Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
> Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
> at java.net.URLClassLoader.findClass(Unknown Source)
> at java.lang.ClassLoader.loadClass(Unknown Source)
> at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
> at java.lang.ClassLoader.loadClass(Unknown Source)
> ... 2 more
> 
> 1. I submit log4j into my maven project
> 2. There is no problem with running in IDEA
> 3. Packed into a jar package,  run the jar package and report an error
>    ![error](https://user-images.githubusercontent.com/48379324/66481776-2cf91b00-ead4-11e9-9145-a99677cc960d.PNG)
>    ![捕获](https://user-images.githubusercontent.com/48379324/66481777-2d91b180-ead4-11e9-9e2c-d53f96642e13.PNG)
